<?php

/**
 * @file
 * Module file for altering hangout operations. 
 * 
 * @Author : Nisith Ranjan Biswal
 */


/*
 * @function menu settings
 * for Dashboard.
 */
function rest_dash_menu() {
    
    $items = array();
    
    $items['dashboard'] = array(
        'title' => 'Dashboard',
        'page callback' => 'dashboard',
        'access callback' => TRUE
    );
    $items['add_menu'] = array(
        'title' => 'Menu Items',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('add_menu'),
        'access callback' => TRUE
    );
    
    $items['get_lat_long'] = array(
        'page callback' => 'get_lat_long',
        'access callback' => TRUE
    );
	
  
    return $items;
}
function rest_dash_theme() {
    
   $themes = array (
        'dashboard_template' => array(
            'template' => 'dashboard_template',
            'arguments' => array(),
        ),
       'gmaps' => array(
            'template' => 'gmaps',
            'arguments' => array(),
        ),
    );
    return $themes;

}

function dashboard() {
    
    $userdata = '';
    $output = '';
    $output .= theme('dashboard_template', array('result' => $userdata));
    
    return $output;
    
}


function get_lat_long() {
 
    $uid = $_POST['uid'];
    $account = user_load($uid);
    
    $profile_data = profile2_load_by_user($account);
    
    $return0 = new stdClass();
    $return0->latitude = $profile_data['restaurant_admin']->field_location['und'][0]['latitude'];
    $return0->longitude = $profile_data['restaurant_admin']->field_location['und'][0]['longitude'];

    print json_encode($return0);exit;
}